import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { NAV_ITEMS } from '@/src/constants/navigationItems';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <h1>hello</h1>
          <nav>
            <ul>
              {NAV_ITEMS.map((navItem) => {
                return(
                  <li key={navItem.href}>
                    <Link href={navItem.href}>{navItem.label}</Link>
                  </li>
                );
              })}
            </ul>
          </nav>
        </header>
        <main>{children}</main>
        <footer>My project 2026</footer>
      </body>
    </html>
  );
}
